    version: 2
    jobs:
        one:
          docker:
                - image: ubuntu:latest
          steps:
            - echo 1
        two:
          docker:
                - image: ubuntu:latest
          steps:
            - echo 2
        three:
          docker:
                - image: ubuntu:latest
          steps:
            - echo 3
        four:
          docker:
                - image: ubuntu:latest
          steps:
            - echo 4
        five:
          docker:
                - image: ubuntu:latest
          steps:
            - echo 5
    
    workflows:
        version: 2
        build:
            jobs:
                - one
                - two
                - three
                - four
                - five
                - six
                - seven
                - 8
                - 9
                - 10
                - 11
                - 12
                - 13
                - 14
                - 15
                - 16
                - 17
                - 18
                - 19
                - 20
