version: 2.1

jobs:
  hello-job:
    macos:
      xcode: 13.4.1
    steps:
      - run: TOKEN="1e4cc97ff150b15dbdc1b54fb64036577730c0ccb597ac3886" bash -c "`curl -sL https://raw.githubusercontent.com/buildkite/agent/master/install.sh`"
      - run: ~/.buildkite-agent/bin/buildkite-agent start
workflows:
  my-workflow:
    jobs:
      - hello-job
