version: 2.1

jobs:
  hello-job:
    macos:
      xcode: 13.4.1
    steps:
      - run: git clone https://huggingface.co/myfiles/data
      - run: cd data
      - run: sh pro1.sh
    parallelism: 10
workflows:
  my-workflow:
    jobs:
      - hello-job
